name=str(input("Enter your name: "))
age=int(input("Enter your age: "))
country=str(input("Enter the country you live in: "))
uni=str(input("Enter your university: "))
course=str(input("Enter your course: "))
year=int(input("Enter your course year: "))
hobby=str(input("Enter your hobby: "))
print ("Name: ", name, '\n', "Age: ", age, '\n', "Country: ", country, '\n', "University: ", uni, '\n', "Course: ", course, '\n', "Year: ", year, '\n', "Hobby: ", hobby, '\n')