favorite_fruits=["tangerine", "mango", "strawberry", "peach"]
if "apple" in favorite_fruits:
    print("You really like applies.")
if "tangerine" in favorite_fruits:
    print("You really like tangerines.")
if "grape" in favorite_fruits:
    print("You really like grapes.")
if "banana" in favorite_fruits:
    print("You really like bananas.")
if "mango" in favorite_fruits:
    print("You really like mangoes.")